### ISSUE TITLE
include relations between organization from ROR (or not)

### ISSUE THREAD

**Issue by ml4rrieu** [tsosi-org/tsosi-app#14]
so that a transfert from a research department is displayed in the page of the parent organization

**Comment by blefeuvr** [comment]
As of early 2026, this is what we have for the hierarchy of the 846 entities on which we have a ror id.... Vive la france 🇫🇷 

`parent -> child`

<img width="2000" height="2000" alt="Image" src="https://github.com/user-attachments/assets/af0a2faa-d8e5-4775-bd6d-bd9214a86eec" />  

  
And this is all entities that have multiple parents:  
```YAML
Centre de Biologie et de Gestion des Populations:
- Institut National de Recherche pour l'Agriculture, l'Alimentation et l'Environnement
- Institut de Recherche pour le Développement
Institut Sophia Agrobiotech:
- Institut National de Recherche pour l'Agriculture, l'Alimentation et l'Environnement
- Centre National de la Recherche Scientifique
- Université Côte d'Azur
Institut des Sciences de l'Evolution de Montpellier:
- École Pratique des Hautes Études
- Centre National de la Recherche Scientifique
- Université de Montpellier
- Institut Écologie et Environnement
- Institut de Recherche pour le Développement
Laboratoire d'Excellence TULIP:
- Institut National de Recherche pour l'Agriculture, l'Alimentation et l'Environnement
- Université de Perpignan
- Centre National de la Recherche Scientifique
Laboratoire de Linguistique Formelle:
- Centre National de la Recherche Scientifique
- Université Paris Cité
'Lib4RI - Library for the Research Institutes within the ETH Domain: Eawag, Empa, PSI & WSL':
- Swiss Federal Institute for Forest, Snow and Landscape Research
- Swiss Federal Institute of Aquatic Science and Technology
- Swiss Federal Laboratories for Materials Science and Technology
- Paul Scherrer Institute
Material Physics Center:
- University of the Basque Country
- Consejo Superior de Investigaciones Científicas
```
